name: Trigger auto deployment for sonksuru-demo-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sonksuru-demo-container-AutoDeployTrigger-6828b2ed-5602-4f3c-a315-dff1b25d4fa7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.SONKSURUDEMOCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.SONKSURUDEMOCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tuckcodes/sonksuru-demo-container:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SONKSURUDEMOCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sonksuru-demo-container -g sonksuru --server docker.io --username  ${{ secrets.SONKSURUDEMOCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.SONKSURUDEMOCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n sonksuru-demo-container -g sonksuru --image tuckcodes/sonksuru-demo-container:${{ github.sha }}
